[workspace]
default-members = ["runner"]
members = [
  # Runner tool
  "runner",
  # Common utility functions
  "utils",

  "day1",
  "day2",
  "day3",
  "day4",
  "day5",
  "day6",
  "day7",
  "day8",
]
